version: '3.8'
services:
  app:
    image: php:8.1-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=login

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=rizz_db
      - MYSQL_USER=rizz_user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
